# Site settings
title: Michael Falgien
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Falgien
user_description: Hi, I'm Michael! I'm an East Bay Area Native and recent graduate of Arizona State University. For my senior capstone I contributed to creating the <a href="http://www.irondb.org" target="_blank">Iron Meteorite Database</a> for ASU and NASA as part of the Psyche 16 mission launching in 2027. <br> <br>In my free time I enjoy watching and going to baseball games (go A's!) and playing Overwatch. Currently I'm working on a react application to display a PC player's statistics. You can try it out <a href="https://overwatch-stats-react-card.herokuapp.com/" target="_blank">here</a> by using my battletag MFalg-1174.
user_title: Software Engineer
email: mfalgien@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-144200281-1"

exclude: ["package.json", "src", "node_modules"]
