# Site settings
title: Michael Falgien
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "www.michaelfalgien.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Falgien
user_description: Hi, I'm Michael! More to come soon...
user_title: Software Engineer
email: mfalgien@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
